spring:
  data:
    mongodb:
      auto-index-creation: true

product-management:
  currency:
    base-url: https://api.exchangeratesapi.io

server:
  servlet:
    context-path: /product-management
  port: 8080
